version: "3"

includes:
  common: ./build/Taskfile.common.yml
  windows: ./build/Taskfile.windows.yml
  darwin: ./build/Taskfile.darwin.yml
  linux: ./build/Taskfile.linux.yml

vars:
  APP_NAME: "curfree"
  BIN_DIR: "bin"
  VITE_PORT: "{{.WAILS_VITE_PORT | default 9245}}"

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: "{{OS}}:build"

  package:
    summary: Packages a production build of the application
    cmds:
      - task: "{{OS}}:package"

  run:
    summary: Runs the application
    cmds:
      - task: "{{OS}}:run"

  dev:
    summary: Runs the application in development mode
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}
  darwin:build:universal:
    summary: Builds darwin universal binary (arm64 + amd64)
    cmds:
      - task: darwin:build
        vars:
          ARCH: amd64
      - mv {{.BIN_DIR}}/{{.APP_NAME}} {{.BIN_DIR}}/{{.APP_NAME}}-amd64
      - task: darwin:build
        vars:
          ARCH: arm64
      - mv {{.BIN_DIR}}/{{.APP_NAME}} {{.BIN_DIR}}/{{.APP_NAME}}-arm64
      - lipo -create -output {{.BIN_DIR}}/{{.APP_NAME}} {{.BIN_DIR}}/{{.APP_NAME}}-amd64 {{.BIN_DIR}}/{{.APP_NAME}}-arm64
      - rm {{.BIN_DIR}}/{{.APP_NAME}}-amd64 {{.BIN_DIR}}/{{.APP_NAME}}-arm64

  darwin:package:universal:
    summary: Packages darwin universal binary (arm64 + amd64)
    deps:
      - darwin:build:universal
    cmds:
      - task: darwin:create:app:bundle

  darwin:package:all:
    summary: Packages both arm64 and universal builds with zip and dmg
    cmds:
      # Build and package arm64 version
      - task: darwin:package
      - mkdir -p {{.BIN_DIR}}/packages
      - ditto -c -k --keepParent {{.BIN_DIR}}/{{.APP_NAME}}.app {{.BIN_DIR}}/packages/{{.APP_NAME}}-arm64.zip
      - create-dmg --volname "{{.APP_NAME}}-arm64" --volicon "build/icons.icns" --icon "{{.APP_NAME}}.app" 128 128 --hide-extension "{{.APP_NAME}}.app" --app-drop-link 384 128 "{{.BIN_DIR}}/packages/{{.APP_NAME}}-arm64.dmg" "{{.BIN_DIR}}/{{.APP_NAME}}.app"

      # Build and package universal version
      - task: darwin:package:universal
      - ditto -c -k --keepParent {{.BIN_DIR}}/{{.APP_NAME}}.app {{.BIN_DIR}}/packages/{{.APP_NAME}}-universal.zip
      - create-dmg --volname "{{.APP_NAME}}-universal" --volicon "build/icons.icns" --icon "{{.APP_NAME}}.app" 128 128 --hide-extension "{{.APP_NAME}}.app" --app-drop-link 384 128 "{{.BIN_DIR}}/packages/{{.APP_NAME}}-universal.dmg" "{{.BIN_DIR}}/{{.APP_NAME}}.app"
