// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class CursorConfig {
    /**
     * Creates a new CursorConfig instance.
     * @param {Partial<CursorConfig>} [$$source = {}] - The source object to create the CursorConfig.
     */
    constructor($$source = {}) {
        if (!("telemetry.machineId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["telemetry.machineId"] = "";
        }
        if (!("telemetry.macMachineId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["telemetry.macMachineId"] = "";
        }
        if (!("telemetry.devDeviceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["telemetry.devDeviceId"] = "";
        }
        if (!("telemetry.sqmId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["telemetry.sqmId"] = "";
        }
        if (!("isReadOnly" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isReadOnly"] = false;
        }
        if (!("configPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CursorConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CursorConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CursorConfig(/** @type {Partial<CursorConfig>} */($$parsedSource));
    }
}
