name: Release
on:
  push:
    tags:
      - "v*" # 触发标签格式为 v开头，例如 v1.0.0

jobs:
  release:
    name: Release
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: cd frontend && npm install

      - name: Install wails
        run: |
          go install -v github.com/wailsapp/wails/v3/cmd/wails3@latest
          wails3 doctor

      - name: Install appdmg
        run: npm install -g appdmg

      - name: Build All Versions
        run: |
          # 使用新的 task 构建所有版本
          wails3 task darwin:package:all

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/packages/curfree-universal.zip
            bin/packages/curfree-universal.dmg
            bin/packages/curfree-arm64.zip
            bin/packages/curfree-arm64.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 